### ISSUE TITLE
question about nostr-tools dep

### ISSUE THREAD

**Issue by shobitb** [dyegolara/nostr-attached#1]
hi!  this is more of a question, rather than an issue.  i noticed your dependency on nostr-tools.  how are you getting around the fact that nostr-tools depends transitively (via the noble/secp256k1 library) on the crypto module, which is not available in react-native?

**Comment by andrerfneves** [comment]
Same question

**Comment by dyegolara** [comment]
I've been busy with my job, but I'll look for a solution for this today, I found that iOS does not have an issue so far, but android throws an error for BigInt missing, ergo crypto.
I'm thinking on some polyfill maybe

**Comment by shobitb** [comment]
I was able to resolve the BigInt issue by using react native 0.70.0 and the hermes engine. Facebook added support for that recently. But it's the crypto module that is not available in RN which causes problems. I think you can still use nostr-tools except for the functions in nip04.ts and the keys.ts.

**Comment by dyegolara** [comment]
this is what I will use: https://docs.expo.dev/versions/v47.0.0/sdk/crypto/
